# @format

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hamzazahid-com-tls
spec:
  secretName: hamzazahid-com
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: hamzazahid.com
  dnsNames:
    - hamzazahid.com
    - www.hamzazahid.com
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - hamzazahid.com
          - www.hamzazahid.com
