# @format

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: postgres
  template:
    metadata:
      labels:
        component: postgres
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: database-parsistent-volume-claim
      containers:
        - name: postgres
          image: postgres
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgres/data
              subPath: postgres
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgress-secret # this is generci secret_name
                  key: postgres-user # this is generci secret key pair
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgress-secret # this is generci secret_name
                  key: postgres-password # this is generci secret key pair
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgress-secret # this is generci secret_name
                  key: postgres-db-name # this is generci secret key pair
